### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by agners** [home-assistant-libs/iotawattpy#1]
From time to time the library raises an exception as follows:

```
2023-01-24 04:44:49.530 ERROR (MainThread) [homeassistant.components.iotawatt.coordinator] Unexpected error fetching iotawatt data: 'NoneType' object has no attribute 'text' 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/iotawatt/coordinator.py", line 76, in _async_update_data
    await self.api.update(lastUpdate=self._last_run)
  File "/usr/local/lib/python3.10/site-packages/iotawattpy/iotawatt.py", line 76, in update
    await self._refreshSensors(timespan, lastUpdate)
  File "/usr/local/lib/python3.10/site-packages/iotawattpy/iotawatt.py", line 161, in _refreshSensors
    query = query.text
AttributeError: 'NoneType' object has no attribute 'text'
```

Right before the stack trace the following error is printed:

```
2023-01-24 04:44:49.520 ERROR (MainThread) [iotawattpy.connection] Err: 
```

**Comment by agners** [comment]
This has been reported upstream in https://github.com/gtdiehl/iotawattpy/issues/6 along with a potential PR https://github.com/gtdiehl/iotawattpy/pull/16 to fix the problem. That said, I am not convinced that the proposed solution is the way to address the problem.

The error is printed at https://github.com/home-assistant-libs/iotawattpy/blob/v0.1.0/iotawattpy/connection.py#L45. What confuses me is that the exception seems not to print as a string. I wonder what exception we are dealing with exactly.

@F13 you claim in https://github.com/gtdiehl/iotawattpy/pull/16#issuecomment-1397083418 that it is a timeout. Are you sure about this? Then maybe increasing the timeout is the way to go?

I think I'd prefer to remove the exception handler in the `__open` function so that the exception is bubbling up and showing clearly. Then we can add sensible handlers higher up where needed.

**Comment by F13** [comment]
I'm quite sure it's a timeout. The offending object is ultimately an `httpx` response object, which appears to be `None` if the request times out. You can try it yourself - run modify `example.py` to have a very short timeout and you'll see the error quickly. Modify the `AsyncClient` instantiation on line 23 like this:
```
self.session = AsyncClient(timeout=httpx.Timeout(0.1))
```
In my case, that give me one of these errors (although admittedly in a slightly different spot in the code, but it seems to be the same situation) within a couple seconds.

In my opinion, the best fix here is to catch the failed request, print a warning to the log, and simply not update the sensors this round. Additionally, allow users to config the timeout. If there are no objections, I can move on this approach.

In my opinion, httpx is weird to work with, and my *personal* preference would be to move to a different library, but that's a discussion for another time :)

**Comment by agners** [comment]
> In my opinion, the best fix here is to catch the failed request, print a warning to the log, and simply not update the sensors this round.

Agreed, question is what level we catch. Returning None and existing that way seems not nice to me?

> Additionally, allow users to config the timeout. If there are no objections, I can move on this approach.

I would not make it configurable, I think we can pick a reasonable value here. Default is 5s, which seems to be too low for certain situations (on that device). So let's just go with 20s or even 30s and see if they still appear.

**Comment by F13** [comment]
In theory, `httpx` should be sending a `TimeoutException` somewhere. I'll try to figure out if that's being caught somewhere and we can handle it more appropriately.

**Comment by agners** [comment]
> The above catches the timeout exception (along with any other HTTP exceptions). It logs the error (which is empty, for some reason),

I really wonder why it is empty. I am tempted to just remove the exception handler to get a proper stack trace/exception in the logs :smile: 

> I don't see an obvious method for handling a potentially-failed HTTP request without just checking whether it succeeded 

IMHO, at the very least we should tell the user why the HTTP request failed (and this is not given with the proposed fix).

**Comment by F13** [comment]
> at the very least we should tell the user why the HTTP request failed

Agreed completely! If we removed error handling and let the exception raise, that might just be more useful. If that exception is still empty, we could always re-raise based on the exception type. (one for timeout with a helpful message, one more general with a less specific message)

**Comment by llamafilm** [comment]
I was able to reproduce this error and identify the exception like this:
```python
import asyncio
import httpx

try:
    asyncio.run(httpx.AsyncClient().get('http://192.168.20.32/status?wifi=yes'))
except Exception as e:
    print(type(e))
```

I configured my router to randomly drop 90% of packets destined for IotaWatt and then ran this code several times.  I saw two different exceptions, `ConnectTimeout` and `ReadTimeout`.
