### ISSUE TITLE
Ownership transfer of the PyPI project

### ISSUE THREAD

**Issue by agners** [home-assistant-libs/iotawattpy#5]
Since the upstream project (and with it the [iotawattpy PyPI project](https://pypi.org/project/iotawattpy/)) appears to be abandoned, @llamafilm offered in https://github.com/gtdiehl/iotawattpy/issues/19#issuecomment-1396223601 to trigger a transfer as per [PEP 541](https://peps.python.org/pep-0541/).

@llamafilm I've made an initial v0.1.1 could you trigger the ownership transfer? My user on PyPI is [agners](https://pypi.org/user/agners/).

**Comment by llamafilm** [comment]
Sure, here it is: https://github.com/pypi/support/issues/2583

**Comment by agners** [comment]
It is a bit annoying that this takes that long.

@llamafilm  Did you try to reach @gtdiehl three times as required by PEP 541?

> The user of the Package Index is solely responsible for being reachable by the Package Index maintainers for matters concerning projects that the user owns. In every case where contacting the user is necessary, the maintainers will try to do so at least three times, using the following means of contact:

Otherwise maybe lets just create a new project, it is easy to switch for our use case.

**Comment by llamafilm** [comment]
Yes I did. I don’t know why this process is so slow. 😕

**Comment by llamafilm** [comment]
I made a HACS version of the Iotawatt integration for my own use because of the Unique ID issue.  There I was able to point to this repo as a requirement, avoiding pypi.  Here it is in case you get tired of waiting for the ownership transfer: https://github.com/llamafilm/iotawatt-hacs

**Comment by agners** [comment]
Ok, gave up on that and created a new PyPI repository [ha-iotawattpy](https://pypi.org/project/ha-iotawattpy/).

A PR for HA Core to use this library is pending, see https://github.com/home-assistant/core/pull/93830.

Closing this issue.
